### ISSUE TITLE
Provide support for validation of baseline items with value 'configured'

### ISSUE THREAD

**Issue by tmaestrini** [tmaestrini/easyGovernance#28]
Many baseline items have to be defined specifically (for example in a customer's context). Upon this, the baseline schema and the validation process must be extended. 

When a baseline item is defined as `configured`, an appropriate definition of the configuration must follow. The configuration contains all necessary values that have to be configured specifically.

**Example**: `M365.IAM.1-2.1`. The baseline item `CustomDomainNames` for `MicrosoftEntraID` needs to be configured:
```yaml
Configuration:
  - enforces: MicrosoftEntraID
    with:
      CustomDomainNames: configured # Specifies whether custom domain names are configured.
```

From now on, instead of providing a `string` value (such as "`true`" or "`4392`" or `"configured"`) the configuration snippet needs to be extended by either an `array` or an `object` value as follows:
```yaml
Configuration:
  - enforces: MicrosoftEntraID
    with:
      CustomDomainNames: 
        - customdomainname.it
        - seconddomainname.com
        - thirddomainname.ch
```
**This example defines three custom domain names** that __must__ be included in the baseline item `CustomDomainNames`. 

> [!NOTE]
> The value `configured` mustn't be used anymore. All `configured` values of an according baseline items have to be properly declared.
