### ISSUE TITLE
Add URL links in sector "manual" in output

### ISSUE THREAD

**Issue by dako365** [tmaestrini/easyGovernance#7]
In the "Manual" section of the output after validation, it would be great if the URL links were stored for the individual objects. 
This would make it much easier for the user to find the relevant setting in the Admin Center.

**Comment by sympmarc** [comment]
I like how the M365 CLI provides help when you use `spfx upgrade`. It outputs a Markdown file as well as fiving you the exact commands you can run to do the upgrade. This is a different scenario, but that concept seems to apply.

**Comment by tmaestrini** [comment]
Fantastic! Will tske that one on the bucket list and work on it asap!

**Comment by tmaestrini** [comment]
UPDATE!
Referring to the baseline 5.2 (for SharePoint Online), the `references` array stands as placeholder for documentation of any baseline setting. The according setting in the `references` array can be a link to a configuration panel, additional text or whatever kind you need to give as a "hint" for the administrator; e.g.:
```yaml
 # intentionally omitted
  - enforces: AccessControl
    with: 
      ConditionalAccessPolicy: AllowLimitedAccess # Blocks or limits access to SharePoint and OneDrive content from un-managed devices.
      BrowserIdleSignout: true
      BrowserIdleSignoutMinutes: 60
      BrowserIdleSignoutWarningMinutes: 5
      LegacyAuthProtocolsEnabled: false # Setting this parameter prevents Office clients using non-modern authentication protocols from accessing SharePoint Online resources
    references:
      - BrowserIdleSignout: ${{tenantAdminUrl}}/_layouts/15/online/AdminHome.aspx#/accessControl/IdleSession
```

 In case the validation fails, the according reference will be returned (if set in baseline policy).
